INFO       - 2024-06-19 18:00:51,666 - client          : logging in using static token
INFO       - 2024-06-19 18:00:53,453 - gateway         : Shard ID None has connected to Gateway (Session ID: edcc4024c110f9c2895f35577caf0495).
ERROR      - 2024-06-19 18:01:06,676 - tree            : Ignoring exception in command tree
Traceback (most recent call last):
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1221, in _call
    command, options = self._get_app_command_options(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1125, in _get_app_command_options
    raise CommandNotFound(name, parents)
discord.app_commands.errors.CommandNotFound: Application command 'ping' not found
ERROR      - 2024-06-19 18:02:17,927 - tree            : Ignoring exception in command tree
Traceback (most recent call last):
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1221, in _call
    command, options = self._get_app_command_options(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1125, in _get_app_command_options
    raise CommandNotFound(name, parents)
discord.app_commands.errors.CommandNotFound: Application command 'ping' not found
ERROR      - 2024-06-19 18:02:35,440 - tree            : Ignoring exception in command tree
Traceback (most recent call last):
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1221, in _call
    command, options = self._get_app_command_options(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1125, in _get_app_command_options
    raise CommandNotFound(name, parents)
discord.app_commands.errors.CommandNotFound: Application command 'katakan' not found
INFO       - 2024-06-19 18:58:37,000 - gateway         : Shard ID None has successfully RESUMED session edcc4024c110f9c2895f35577caf0495.
INFO       - 2024-06-19 19:23:12,780 - gateway         : Shard ID None has successfully RESUMED session edcc4024c110f9c2895f35577caf0495.
INFO       - 2024-06-19 19:36:41,712 - gateway         : Shard ID None has successfully RESUMED session edcc4024c110f9c2895f35577caf0495.
